export const ERROR_CATALOG = {
  ADULTS_ONLY: {
    hr: "Registracija je dopuštena samo punoljetnima (18+).",
    en: "Only adults (18+) can register.",
    de: "Nur Erwachsene (18+) können sich registrieren.",
    sl: "Registracija je dovoljena le polnoletnim (18+).",
    bs: "Registracija je dozvoljena samo punoljetnima (18+).",
    sr: "Registracija je dozvoljena samo punoletnima (18+).",
    it: "La registrazione è consentita solo ai maggiorenni (18+).",
    hu: "Csak nagykorúak (18+) regisztrálhatnak.",
    pl: "Rejestracja tylko dla pełnoletnich (18+).",
    cs: "Registrace je povolena pouze plnoletým (18+).",
    fr: "L'inscription est réservée aux personnes majeures (18 ans ou plus).",
    es: "El registro está permitido solo para mayores de edad (18+).",
    sk: "Registrácia je povolená len plnoletým (18+).",
  },
  SEEKING_AGE_UNDER_MIN: {
    hr: "Tražena dob ne smije biti manja od 18 godina.",
    en: "The seeking age range cannot be below 18.",
    de: "Das gesuchte Alter darf nicht unter 18 Jahren liegen.",
    sl: "Iskana starost ne sme biti manjša od 18 let.",
    bs: "Tražena dob ne smije biti manja od 18 godina.",
    sr: "Tražena starost ne sme biti manja od 18 godina.",
    it: "L'età cercata non può essere inferiore a 18 anni.",
    hu: "A keresett életkor nem lehet 18 év alatt.",
    pl: "Szukany wiek nie może być niższy niż 18 lat.",
    cs: "Hledaný věk nesmí být nižší než 18 let.",
    fr: "L'âge recherché ne peut pas être inférieur à 18 ans.",
    es: "La edad buscada no puede ser menor de 18 años.",
    sk: "Hľadaný vek nesmie byť nižší ako 18 rokov.",
  },
  SEEKING_AGE_OVER_MAX: {
    hr: "Tražena dob ne smije biti veća od 99 godina.",
    en: "The seeking age range cannot be above 99.",
    de: "Das gesuchte Alter darf nicht über 99 Jahre liegen.",
    sl: "Iskana starost ne sme biti večja od 99 let.",
    bs: "Tražena dob ne smije biti veća od 99 godina.",
    sr: "Tražena starost ne sme biti veća od 99 godina.",
    it: "L'età cercata non può essere superiore a 99 anni.",
    hu: "A keresett életkor nem lehet 99 év felett.",
    pl: "Szukany wiek nie może być wyższy niż 99 lat.",
    cs: "Hledaný věk nesmí být vyšší než 99 let.",
    fr: "L'âge recherché ne peut pas dépasser 99 ans.",
    es: "La edad buscada no puede ser mayor de 99 años.",
    sk: "Hľadaný vek nesmie byť vyšší ako 99 rokov.",
  },
  SEEKING_AGE_INVERTED: {
    hr: "Najmanja tražena dob mora biti manja ili jednaka najvećoj.",
    en: "Minimum seeking age must be less than or equal to maximum.",
    de: "Das Mindestalter muss kleiner oder gleich dem Höchstalter sein.",
    sl: "Najnižja iskana starost mora biti manjša ali enaka najvišji.",
    bs: "Najmanja tražena dob mora biti manja ili jednaka najvećoj.",
    sr: "Najmanja tražena starost mora biti manja ili jednaka najvećoj.",
    it: "L'età minima cercata deve essere minore o uguale alla massima.",
    hu: "A minimális keresett életkor nem lehet nagyobb a maximálisnál.",
    pl: "Minimalny szukany wiek musi być mniejszy lub równy maksymalnemu.",
    cs: "Minimální hledaný věk musí být menší nebo roven maximálnímu.",
    fr: "L'âge minimum recherché doit être inférieur ou égal au maximum.",
    es: "La edad mínima buscada debe ser menor o igual que la máxima.",
    sk: "Minimálny hľadaný vek musí byť menší alebo rovný maximálnemu.",
  },
  EMAIL_EXISTS: {
    hr: "Email adresa je već registrirana.",
    en: "Email already exists.",
    de: "E-Mail existiert bereits.",
    sl: "E-pošta že obstaja.",
    bs: "Email adresa već postoji.",
    sr: "Email adresa već postoji.",
    it: "Email già registrata.",
    hu: "Az e-mail cím már létezik.",
    pl: "Adres email jest już zarejestrowany.",
    cs: "E-mail je již registrován.",
    fr: "Cet e-mail est déjà enregistré.",
    es: "Este correo ya está registrado.",
    sk: "Tento e-mail je už zaregistrovaný.",
  },
  INVALID_PAYLOAD: {
    hr: "Neispravni podaci. Provjeri unos i pokušaj ponovo.",
    en: "Invalid data. Check your input and try again.",
    de: "Ungültige Daten. Prüfe deine Eingaben und versuche es erneut.",
    sl: "Neveljavni podatki. Preverite vnos in poskusite znova.",
    bs: "Neispravni podaci. Provjeri unos i pokušaj ponovo.",
    sr: "Neispravni podaci. Proveri unos i pokušaj ponovo.",
    it: "Dati non validi. Controlla l'inserimento e riprova.",
    hu: "Érvénytelen adatok. Ellenőrizd a bevitelt, és próbáld újra.",
    pl: "Nieprawidłowe dane. Sprawdź wpis i spróbuj ponownie.",
    cs: "Neplatná data. Zkontrolujte zadání a zkuste to znovu.",
    fr: "Données invalides. Vérifiez votre saisie et réessayez.",
    es: "Datos no válidos. Revisa la información e inténtalo de nuevo.",
    sk: "Neplatné údaje. Skontrolujte zadanie a skúste znova.",
  },
  INVALID_CODE: {
    hr: "Kod nije ispravan ili je istekao.",
    en: "Invalid or expired code.",
    de: "Ungültiger oder abgelaufener Code.",
    sl: "Neveljavna ali potekla koda.",
    bs: "Neispravan ili istekao kod.",
    sr: "Neispravan ili istekao kod.",
    it: "Codice non valido o scaduto.",
    hu: "A kód érvénytelen vagy lejárt.",
    pl: "Kod jest nieprawidłowy lub wygasł.",
    cs: "Kód je neplatný nebo vypršel.",
    fr: "Code invalide ou expiré.",
    es: "Código no válido o caducado.",
    sk: "Kód je neplatný alebo vypršal.",
  },
  INVALID_CREDENTIALS: {
    hr: "Email ili lozinka nisu ispravni.",
    en: "Invalid email or password.",
    de: "Ungültige E-Mail oder Passwort.",
    sl: "Neveljavna e-pošta ali geslo.",
    bs: "Neispravan email ili lozinka.",
    sr: "Neispravan email ili lozinka.",
    it: "Email o password non corretti.",
    hu: "Érvénytelen e-mail vagy jelszó.",
    pl: "Nieprawidłowy email lub hasło.",
    cs: "Neplatný e-mail nebo heslo.",
    fr: "E-mail ou mot de passe incorrect.",
    es: "Correo o contraseña incorrectos.",
    sk: "E-mail alebo heslo je nesprávne.",
  },
  EMAIL_NOT_VERIFIED: {
    hr: "Email još nije potvrđen. Provjeri pristiglu poštu.",
    en: "Email not verified. Check your inbox.",
    de: "E-Mail nicht bestätigt. Prüfe deinen Posteingang.",
    sl: "E-pošta ni potrjena. Preverite prejeta sporočila.",
    bs: "Email nije potvrđen. Provjeri inbox.",
    sr: "Email nije potvrđen. Proveri inbox.",
    it: "Email non ancora verificata. Controlla la posta.",
    hu: "Az e-mail nincs megerősítve. Ellenőrizd a beérkező leveleket.",
    pl: "Email nie został jeszcze potwierdzony. Sprawdź skrzynkę.",
    cs: "E-mail ještě není ověřen. Zkontrolujte schránku.",
    fr: "E-mail non confirmé. Consultez votre boîte de réception.",
    es: "Correo no confirmado. Revisa tu bandeja de entrada.",
    sk: "E-mail ešte nie je potvrdený. Skontrolujte doručenú poštu.",
  },
  ACCOUNT_SUSPENDED: {
    hr: "Račun je suspendiran. Kontaktiraj podršku.",
    en: "Account suspended. Contact support.",
    de: "Konto gesperrt. Kontaktiere den Support.",
    sl: "Račun je suspendiran. Obrnite se na podporo.",
    bs: "Račun je suspendovan. Kontaktiraj podršku.",
    sr: "Nalog je suspendovan. Kontaktiraj podršku.",
    it: "Account sospeso. Contatta il supporto.",
    hu: "A fiók felfüggesztve. Lépj kapcsolatba a támogatással.",
    pl: "Konto zawieszone. Skontaktuj się z pomocą.",
    cs: "Účet je pozastaven. Kontaktujte podporu.",
    fr: "Compte suspendu. Contactez le support.",
    es: "Cuenta suspendida. Contacta con soporte.",
    sk: "Účet je pozastavený. Kontaktujte podporu.",
  },
  PROFILE_NOT_FOUND: {
    hr: "Profil nije pronađen.",
    en: "Profile not found.",
    de: "Profil nicht gefunden.",
    sl: "Profil ni najden.",
    bs: "Profil nije pronađen.",
    sr: "Profil nije pronađen.",
    it: "Profilo non trovato.",
    hu: "A profil nem található.",
    pl: "Nie znaleziono profilu.",
    cs: "Profil nenalezen.",
    fr: "Profil introuvable.",
    es: "Perfil no encontrado.",
    sk: "Profil sa nenašiel.",
  },
  CAPTCHA_FAILED: {
    hr: "Captcha provjera nije uspjela.",
    en: "Captcha verification failed.",
    de: "Captcha-Überprüfung fehlgeschlagen.",
    sl: "Preverjanje captche ni uspelo.",
    bs: "Captcha provjera nije uspjela.",
    sr: "Captcha provera nije uspela.",
    it: "Verifica captcha fallita.",
    hu: "Captcha ellenőrzés sikertelen.",
    pl: "Weryfikacja captcha nie powiodła się.",
    cs: "Ověření captcha se nezdařilo.",
    fr: "Échec de la vérification captcha.",
    es: "Error en la verificación del captcha.",
    sk: "Overenie captcha zlyhalo.",
  },
  CAPTCHA_REQUIRED: {
    hr: "Potvrdi captchu prije nastavka.",
    en: "Captcha verification required.",
    de: "Captcha-Überprüfung erforderlich.",
    sl: "Preverjanje captche je obvezno.",
    bs: "Captcha provjera je obavezna.",
    sr: "Captcha provera je obavezna.",
    it: "Verifica captcha richiesta.",
    hu: "Captcha ellenőrzés szükséges.",
    pl: "Wymagana weryfikacja captcha.",
    cs: "Vyžaduje se ověření captcha.",
    fr: "Confirmation captcha requise.",
    es: "Se requiere confirmación del captcha.",
    sk: "Vyžaduje sa potvrdenie captcha.",
  },
  INVALID_SUBMISSION: {
    hr: "Neispravan zahtjev.",
    en: "Invalid submission.",
    de: "Ungültige Übermittlung.",
    sl: "Neveljavna oddaja.",
    bs: "Neispravan zahtjev.",
    sr: "Neispravan zahtev.",
    it: "Richiesta non valida.",
    hu: "Érvénytelen beküldés.",
    pl: "Nieprawidłowe zgłoszenie.",
    cs: "Neplatné odeslání.",
    fr: "Requête invalide.",
    es: "Solicitud no válida.",
    sk: "Neplatná požiadavka.",
  },
};

import { SUPPORTED_LOCALES } from './locales.js';

export function parseLocale(acceptLanguage) {
  if (!acceptLanguage || typeof acceptLanguage !== 'string') return 'hr';
  const primary = acceptLanguage.split(',')[0].trim().toLowerCase().split('-')[0];
  if (SUPPORTED_LOCALES.includes(primary)) return primary;
  if (primary.startsWith('en')) return 'en';
  if (primary.startsWith('de')) return 'de';
  return 'hr';
}

export function tError(code, locale = 'hr') {
  const entry = ERROR_CATALOG[code];
  if (!entry) return ERROR_CATALOG.INVALID_PAYLOAD[locale] || ERROR_CATALOG.INVALID_PAYLOAD.en || ERROR_CATALOG.INVALID_PAYLOAD.hr;
  return entry[locale] || entry.en || entry.hr;
}

export function sendError(req, res, status, code, extra = {}) {
  const locale = parseLocale(req.headers['accept-language']);
  return res.status(status).json({
    success: false,
    errorCode: code,
    error: tError(code, locale),
    ...extra
  });
}
